import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import './globals.css'
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="min-h-screen bg-gradient-to-br from-indigo-950 via-purple-900 to-indigo-900 text-white">
          <Navbar></Navbar>{children}
          <footer className="w-full py-4 text-center text-sm text-purple-200 border-t border-white/10 mt-10">
        © {new Date().getFullYear()} MysteryMessage. All rights reserved.
      </footer>
            <Toaster />
            
        </body>
      </AuthProvider>
    </html>
  );
}
